apiVersion: v1
kind: Service
metadata:
  name: dns-service-tcp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "web.default.cluster.local"
spec:
  type: LoadBalancer
    #loadBalancerIP: 172.17.255.10
  loadBalancerIP: 192.168.59.10
  externalTrafficPolicy: Local
  ports:
    - name: dnstcp
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service-udp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "web.default.cluster.local"
spec:
  type: LoadBalancer
    #loadBalancerIP: 172.17.255.10
  loadBalancerIP: 192.168.59.10
  externalTrafficPolicy: Local
  ports:
    - name: dnsudp
      protocol: UDP
      port: 80
      targetPort: 8000
  selector:
    app: web

