---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jane-admin
  namespace: dev
rules: 
  - apiGroups: [""] # 1st API group
    resources: ["pods","services","namespaces","deployments","jobs"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: rolebinding:jane-admin

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jane-admin
subjects:
  - kind: ServiceAccount
    name: jane
    namespace: dev
