---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ken-viewer
  namespace: dev
rules: 
  - apiGroups: [""] # 1st API group
    resources: ["pods"]
    verbs: ["list", "get", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: rolebinding:ken-viewer

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ken-viewer
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev
