apiVersion: v1
data:
  secretkey: eStCdVRPdlRHS3BVaWxiV2NrdEN4TEw2KzY3dDY5NkZwelpwUnJhdlBSaVZuNkVreUdBSFhFdGwrSmpaRVJtYQpzWHBNNWxsZGQ1ZkYwdlJPWmQ5MWM5OGlhK3p5S2RKR2NlQklaSEhEQ1ZzWE1wVEtIU1BBNitJUzdtcXdVZWQyClRRSDBoKzc0b0xQc3hMYUpUV3krYzNrYXIxaWNmNi9PRHpoLzlhSTJoNHM9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
