---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prometheus
  name: carol-viewer
rules: 
  - apiGroups: [""] # 1st API group
    resources: ["pods"]
    verbs: ["list", "get", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding:carol-viewer
  namespace: prometheus

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carol-viewer
subjects:
  - kind: ServiceAccount
    name: carol
    namespace: prometheus
