apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  strategy:
    type: Recreate
    #    type: RollingUpdate
    #    rollingUpdate:
    #      maxUnavailable: 3
    #      maxSurge: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: kaperusov/paymentservice:v0.0.3
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
